import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#ffb47f",
        "on-secondary": "#00354a",
        primary: "#6bfb9a",
        surface: "#0b1326",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#6c3a0f",
        background: "#0b1326",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bccabb",
        "on-primary-container": "#005e2d",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb784",
        "on-primary-fixed-variant": "#005227",
        "on-secondary-container": "#00374d",
        "on-primary": "#003919",
        outline: "#869486",
        "secondary-fixed": "#c4e7ff",
        "inverse-surface": "#dae2fd",
        "surface-container": "#171f33",
        "outline-variant": "#3d4a3e",
        secondary: "#7bd0ff",
        "surface-bright": "#31394d",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#6dfe9c",
        "primary-fixed-dim": "#4de082",
        "on-primary-fixed": "#00210c",
        "surface-variant": "#2d3449",
        "surface-tint": "#4de082",
        "on-background": "#dae2fd",
        "on-secondary-fixed-variant": "#004c69",
        "surface-dim": "#0b1326",
        "on-secondary-fixed": "#001e2c",
        "tertiary-fixed": "#ffdcc6",
        "primary-container": "#4ade80",
        "surface-container-lowest": "#060e20",
        "surface-container-high": "#222a3d",
        "secondary-container": "#00a6e0",
        "on-error": "#690005",
        "secondary-fixed-dim": "#7bd0ff",
        tertiary: "#ffd9c1",
        "surface-container-low": "#131b2e",
        "inverse-primary": "#006d36",
        "on-tertiary": "#4f2500",
        "on-tertiary-fixed": "#301400",
        error: "#ffb4ab",
        "on-tertiary-container": "#794418",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        xl: "32px",
        base: "4px",
        "margin-mobile": "16px",
        xs: "4px",
        lg: "24px",
        md: "16px",
        gutter: "16px",
        sm: "8px",
        "stack-gap": "16px",
        "section-gap": "32px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "display-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-sm": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      keyframes: {
        scan: {
          "0%": { top: "0" },
          "50%": { top: "100%" },
          "100%": { top: "0" },
        },
      },
      animation: {
        scan: "scan 2s infinite",
      },
    },
  },
  plugins: [],
};

export default config;
